version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
        environment:
          FLASK_CONFIG: testing
    steps:
      - add_ssh_keys:
          fingerprints:
            - 62:b3:b1:c1:7d:56:af:06:db:9b:26:70:98:e2:da:23
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            virtualenv helloworld
            . helloworld/bin/activate
            pip install flask pyinstaller
      - run:
          name: Run Tests
          command: |
            . helloworld/bin/activate
            python test_hello_world.py
      - run:
          name: Package app binary
          command: |
            . helloworld/bin/activate
            pyinstaller -F hello_world.py
            mv ~/project/dist/hello_world /tmp/
      - run:
          name: Deploy app to Digital Ocean Server
          command: |
            scp -o StrictHostKeyChecking=no /tmp/hello_world root@hello.dpunks.org:/tmp/
            ssh -o StrictHostKeyChecking=no root@hello.dpunks.org "/bin/bash ./deploy_app.sh"